quiz_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from quizez import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizez.urls', namespace="quizez")),
    path('', views.home, name='home'),

    # leaderboard and result
    path('leaderboard/', views.leaderboards, name='leaderboards'),
    path('results/', views.results, name='results'),



    # Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),

    # addquiz

    path('add_quiz/', views.add_quiz, name='add_quiz'),
    path('add_question/', views.add_question, name='add_question'),
    path('add_options/<int:myid>/', views.add_options, name='add_options'),
    path('delete_question/<int:myid>/',
         views.delete_question, name='delete_question'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizez/urls.py
from django.urls import path

from .views import *

app_name = 'quizez'

urlpatterns = [

    # quiz
    path('main/', QuizListView.as_view(), name='main-view'),
    path('main/<pk>/', quiz_view, name='quiz-view'),
    path('main/<pk>/save/', save_quiz_view, name='save-view'),
    path('main/<pk>/data/', quiz_data_view, name='quiz-data-view'),


]

quizez/models.py
from django.db import models
import random

# Create your models here.

DIFF_CHOICES = (

    ('Easy', 'Easy'),
    ('Intermediate', 'Intermediate'),
    ('Hard', 'Hard')

)


class Quiz(models.Model):
    name = models.CharField(max_length=200)
    topic = models.CharField(max_length=200)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="Duration of quiz in minutes")
    required_score_to_pass = models.IntegerField(
        help_text="Required Score to pass")
    difficulty = models.CharField(
        max_length=12, choices=DIFF_CHOICES, default="Select")

    def __str__(self):
        return f"{self.name} - {self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'

results/models.py
from django.db import models
from quizez.models import *
from django.contrib.auth.models import User
# Create your models here.

class Result(models.Model):
	quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	score = models.FloatField()


	def __str__(self):
		return str(self.pk)

quizez/forms.py
from django import forms
from questions.models import Question
from .models import Quiz
from django.contrib import admin


class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ('name', 'topic', 'difficulty',
                  'number_of_questions', 'time', 'required_score_to_pass')


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('text', 'quiz')

quizez/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from .models import *
from django.contrib.auth import login, logout, authenticate
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import *
from results.models import *
from .forms import QuizForm, QuestionForm
from .models import *
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponse

# Create your views here.


def home(request):
    return render(request, "quizez/home.html")


def signupuser(request):

    if request.method == "GET":
        return render(request, "quizez/signupuser.html")
    else:
        if request.POST["password1"] == request.POST["password2"]:
            try:
                user = User.objects.create_user(
                    request.POST["username"], password=request.POST["password1"]
                )
                user.save()
                login(request, user)
                return redirect("/main")
            except IntegrityError:
                return render(
                    request,
                    "quizez/signupuser.html",
                    {
                        "form": UserCreationForm(),
                        "error": "That username has already been taken. Please choose a new username",
                    },
                )
        else:
            return render(
                request,
                "quizez/signupuser.html",
                {"form": UserCreationForm(), "error": "Passwords did not match"},
            )


def loginuser(request):
    if request.method == "GET":
        return render(request, "quizez/loginuser.html", {"form": AuthenticationForm()})
    else:
        user = authenticate(
            request,
            username=request.POST["username"],
            password=request.POST["password"],
        )
        if user is None:
            return render(
                request,
                "quizez/loginuser.html",
                {
                    "form": AuthenticationForm(),
                    "error": "Username and password did not match",
                },
            )
        else:
            login(request, user)
            return redirect("/main")


@login_required
def logoutuser(request):
    if request.method == "POST":
        logout(request)
        return redirect("home")


class QuizListView(ListView):
    Model = Quiz
    template_name = "quizez/main.html"
    context_object_name = "quiz"

    def get_queryset(self):
        return Quiz.objects.all()


@login_required
def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, "quizez/quiz.html", {"obj": quiz})


@login_required
def quiz_data_view(request, pk):

    quiz = Quiz.objects.get(pk=pk)
    question = []

    for q in quiz.get_questions():
        answer = []
        for a in q.get_answers():
            answer.append(a.text)
        question.append({str(q): answer})
    return JsonResponse(
        {
            "data": question,
            "time": quiz.time,
        }
    )


@login_required
def save_quiz_view(request, pk):
    print(request.POST)

    if is_ajax(request):
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop("csrfmiddlewaretoken")

        for k in data_.keys():
            print("keys ", k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)
        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                print(a_selected)
                questions_answers = Answer.objects.filter(question=q)

                for a in questions_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text
                results.append(
                    {str(q): {"correct_answer": correct_answer, "answered": a_selected}}
                )

            else:
                results.append({str(q): "not answered"})
        final_res = score * multiplier
        print(final_res)
        Result.objects.create(quiz=quiz, user=user, score=final_res)

        return JsonResponse({"passed": True, "score": final_res, "results": results})


@login_required
def leaderboards(request):
    ranking_score = Result.objects.order_by("-score")
    total_count = ranking_score.count()
    context = {
        "ranking_score": ranking_score,
        "total_count": total_count,
    }
    return render(request, "quizez/leaderboard.html", context=context)


@login_required
def results(request):
    results = Result.objects.all()
    return render(request, "quizez/results.html", {"results": results})


# admin only if superuser
@login_required
def add_quiz(request):
    if request.method == "POST":
        form = QuizForm(data=request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.save()
            objs = form.instance
            return render(request, "quizez/add_question.html", {"obj": objs})
    else:
        form = QuizForm()
    return render(request, "quizez/addquiz.html", {"form": form})


@login_required
def add_question(request):
    questions = Question.objects.all()
    questions = Question.objects.filter().order_by("-id")
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "quizez/add_question.html")
    else:
        form = QuestionForm()
    return render(
        request, "quizez/add_question.html", {"form": form, "questions": questions}
    )


@login_required
def delete_question(request, myid):
    question = Question.objects.get(id=myid)
    if request.method == "POST":
        question.delete()
        return redirect("/add_question")
    return render(request, "quizez/delete_question.html", {"question": question})


@login_required
def add_options(request, myid):
    question = Question.objects.get(id=myid)
    QuestionFormSet = inlineformset_factory(
        Question, Answer, fields=("text", "correct", "question"), extra=4
    )
    if request.method == "POST":
        formset = QuestionFormSet(request.POST, instance=question)
        if formset.is_valid():
            formset.save()
            alert = True
            return render(request, "quizez/add_options.html", {"alert": alert})
    else:
        formset = QuestionFormSet(instance=question)
    return render(
        request, "quizez/add_options.html", {"formset": formset, "question": question}
    )


def is_ajax(request):
    return request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest"


def ajax_test(request):
    if is_ajax(request=request):
        message = "This is ajax"
    else:
        message = "Not ajax"
    return HttpResponse(message)

results/views.py
from django.shortcuts import render

# Create your views here.

quizez/templates/quizez/add_options.html
{% block title %} Add Options {% endblock %}

{% block body %}
<div class="container mt-4">
    <form action="/add_options/{{question.id}}/" method="POST"> {% csrf_token %}
        {{ formset.as_p }}
        <button type="submit" class="btn btn-info">Submit</button>
    </form>
</div>
{% endblock %}
{% block js %}
<script>
    {% if alert %}
    alert("Question is added successfully!!!");
    document.location = '/add_question/'
    {% endif %}
</script>
{% endblock %}

quizez/templates/quizez/add_question.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <h1 class="text-center"> {% block title %} Add Question {% endblock %}</h1>
  {% block body %}
  <br>
  <br>
  <div class="container mt-4">
    <form action="/add_question/" method="POST"> {% csrf_token %}
      <h2>Content</h2>
      {{ form.as_p }}
      <button type="submit">Save</button>
    </form>
</head>
<br>
<div class="container"></div>
<table class="table">
  <table id="dtVerticalScrollExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Question</th>
        <th>Quiz</th>
        <th>Delete</th>
      </tr>
    </thead>
    {% for question in questions %}
    <tr>
      <td><a href="/add_options/{{question.id}}/">{{question.text}}</a></td>
      <td>{{question.quiz}}</td>
      <td><a href="/delete_question/{{question.id}}/" class="btn btn-danger">Delete</a></td>
    </tr>
    {% endfor %}
  </table>
  <div> <button><a href="/main">close</a></button></div>
  </div>

  {% endblock %}

quizez/templates/quizez/addquiz.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center">{% block title %}Add Quiz{% endblock %}</h2>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <a href="/main" class="btn btn-secondary">Close</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

quizez/templates/quizez/delete_question.html
{% block title %} Delete Question {% endblock %}

{% block body %}
<div class="container mt-4">
    <h4>Are you sure you want to delete {{question.content}}</h4>
    <br>
    <form action="/delete_question/{{question.id}}/" method="POST">

        {% csrf_token %}
        <a class="btn btn-warning" href="quizez/add_question/">Cancel</a>

        <input class="btn btn-danger" type="submit" value="Delete">
    </form>
</div>

{% endblock %}

quizez/templates/quizez/home.html
{% extends "base.html" %}

{% block content %}
<style>
    body {
        font-family: Verdana;
    }

    .box {
        width: 500px;
        height: 40px;
        border: 2px solid #000;
        margin: 0 auto 15px;
        text-align: center;
        padding: 5px;
        font-weight: bold;
        border-radius: 10px;
    }

    .error {
        background-color: #EBB1B1;
        border-color: #973939;
        color: #973939;
    }
</style>
<br>

<br>
<br>
<br>
<br>
<br>
<div class="row justify-content-center mt-5">
    <div class="col-md-7 text-center">

        
        <p>This web application will allow you to create and take tests</p>
        
        <a role="button" class="btn btn-primary btn-lg" href="/signup">Start</a>
    </div>

</div>
<footer>
    <br>
    <br>
</footer>
{% endblock %}

quizez/templates/quizez/leaderboard.html
{% extends 'base.html' %}
{% block title %} Let's Quiz | Leaderboard {% endblock title %}
{% block content %}
<div class="container">
  <h1 class="text-center my-4"><span class="badge badge-light"><i class="fa fa-trophy" aria-hidden="true"></i> TOP
      {{total_count}} PLAYERS <i class="fa fa-trophy" aria-hidden="true"></i></span></h1>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Position</th>
        <th>Username</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      {% for rank in ranking_score %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{rank.user}}</td>
        <td>{{rank.score}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <div>

  </div>
</div>
{% endblock content %}

quizez/templates/quizez/loginuser.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2>Login</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" class="form-control" id="username">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" id="password">
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
        <hr>
        <div class="text-center">
            Need an account? <a href="{% url 'signupuser' %}">Sign Up here</a>
        </div>
    </div>
</div>
<footer>
    <br>
    
</footer>
{% endblock %}

quizez/templates/quizez/main.html
{% extends 'base.html' %}
{% load static %}


{% block scripts %}

<script src="{% static 'quizez/main.js' %}" defer></script>

{% endblock scripts %}

{% block title %}


{% endblock title %}



{% block content %}

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Are you ready?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body-confirm">
        <p>Read the question carefully</p>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
        <button type="button" id="start-button" class="btn btn-success">Yes</button>
      </div>
    </div>
  </div>
</div>
<h1 class="text-center">Dashboard </h1>
<div class="h1">
  Quiz List
</div>

{% for obj in quiz %}

<button class="btn btn-link modal-button" data-pk="{{obj.pk}}" data-quiz="{{obj.name}}"
  data-questions="{{obj.number_of_questions}}" data-difficulty="{{obj.difficulty}}" data-time="{{obj.time}}"
  data-pass="{{obj.required_score_to_pass}}" data-toggle="modal" data-target="#exampleModal">

  <div class="card" style="width: 21rem;">
    <img class="card-img-top" src="https://images.hdqwalls.com/download/python-logo-4k-i6-1280x1024.jpg"
      alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"> {{obj.name}}</h5>
      <p class="card-text">Python {{obj.topic}}.</p>
      <a href="#" class="btn btn-primary">Start</a>
    </div>
  </div>


</button>

{% endfor %}


{% endblock content %}

quizez/templates/quizez/quiz.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
<script>alert('Read the question carefully, Goodluck!')</script>
<script src="{% static 'quizez/quiz.js' %}" defer></script>

{% endblock scripts %}

{% block title %}

Quiz Of {{obj.name}}

{% endblock title %}



{% block content %}



<div class="row">
	<div class="col mb-3">
		<b>{{obj.name}}</b><br>
		Required score to pass <i><b>{{obj.required_score_to_pass}} %</b></i>
	</div>

	<div class="col text-right mb-3" id="timerbox">

	</div>
</div>


<hr>
<form id="form-quiz" class="mt-3 mb-3">

	{% csrf_token %}
	<div id="quiz-box">



	</div>

	<button type="submit" class="btn btn-primary mt-3">Save</button>


</form>

<div id="score-box"></div>
<div id="result-box"></div>
<footer>
	<a class="btn btn-warning" href="{% url 'quizez:main-view' %}">Close</a>
</footer>


{% endblock content %}

quizez/templates/quizez/results.html
{% block title %} Results {% endblock %}

{% block body %}
<div class="container mt-4">
  <br>
  <table class="table">
    <thead>
      <tr>
        <th>User</th>
        <th>Quiz</th>
        <th>Score</th>
      </tr>
    </thead>
    {% for result in results %}
    <tr>
      <td>{{ forloop.counter }}</td>
      <td>{{result.user}}</td>
      <td>{{result.score}}</td>
      <td>{{result.quiz}}</td>
    </tr>
    {% endfor %}
  </table>
  <button style="background-color: #ffcc00; border-color: #ffcc00;"><a href="/main">close</a></button>
</div>
{% endblock %}

quizez/templates/quizez/signupuser.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2>Sign Up</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know
                    if someone has taken it already.</small>
            </div>
            <div class="form-group">
                <label for="password1">Password</label>
                <input type="password" name="password1" class="form-control" id="password1">
            </div>
            <div class="form-group">
                <label for="password2">Confirm Password</label>
                <input type="password" name="password2" class="form-control" id="password2">
            </div>
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>
        <hr>
        <div class="text-center">
            Do you already have an account? <a href="{% url 'loginuser' %}">Login here</a>
        </div>
    </div>
</div>
<footer>
    <br>
</footer>
{% endblock %}